### ISSUE TITLE
R script to turn numbers nicely into strings for plotting reasons

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/scripting-templates#2]
Sometimes plots use for labelling and sorting of data numeric values which create problems in plot design, e.g. an x-axis sorting of 0,1,11,12,2,3,...
Features of the script:
- adding 0 to make integer into unique length strings. e.g. 00,01,02,03,...,11,12
like with String Manipulator: substr(join("0",string($field$)),length(join("0",string($field$)))-2,2)
- handle multiple columns
- optional automates column duplication and rename (e.g. field > field.string)
handle digits, turn numbers to fixed digits, e.g. 0.00,1.11,2.22,...
- digit handling and 0 adding in combination
- adding pre-/suffixes e.g. 00.0nM,01.11nM,02.22nM
anything else?

(Martin)

**Comment by stoeter** [comment]
There is a R snippet template under section utilities that does this:
Convert numbers to defined text/string
a) done
b) option to use flow variable
c) append column with suffix
d) done
e) not done but coudl be done with string manipulator

The new Number Formatter node in the new HCS tools release could cover these needs as well and would make this snippet obsolete.
